# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xiechengItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('hot', models.CharField(max_length=100)),
                ('day', models.DateField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parkList',
            },
        ),
    ]
