# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiechengapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, unique=True)),
                ('upwd', models.CharField(max_length=100)),
                ('utoken', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
