# Generated by Django 2.2 on 2021-05-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiechengapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('heat', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
