# Generated by Django 2.2 on 2021-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiechengapp', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
