# Generated by Django 2.2 on 2021-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiechengapp', '0004_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='heat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
